# Generated by Django 6.0.9 on 2026-10-07 20:21

import django.core.validators
import django.db.models.deletion
import django_mongodb_backend.fields
from django.db import migrations, models
from django.db.migrations.exceptions import IrreversibleError


class CreateOrAdoptModel(migrations.CreateModel):
    """Adopta las colecciones creadas en Atlas sin borrarlas ni recrearlas."""

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        model = to_state.apps.get_model(app_label, self.name)
        if not self.allow_migrate_model(schema_editor.connection.alias, model):
            return
        existing = schema_editor.connection.introspection.table_names()
        if model._meta.db_table in existing:
            # Backend 6.0.4: mismo constructor de índices que create_model().
            schema_editor._create_model_indexes(model)
        else:
            schema_editor.create_model(model)

    def database_backwards(self, app_label, schema_editor, from_state, to_state):
        raise IrreversibleError("Esta migración conserva las colecciones compartidas de Atlas.")


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        CreateOrAdoptModel(
            name='Contador',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=32, unique=True)),
                ('valor', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'contadores',
            },
        ),
        CreateOrAdoptModel(
            name='Participante',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=32, unique=True)),
                ('nombre', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'participantes',
                'ordering': ['codigo'],
            },
        ),
        CreateOrAdoptModel(
            name='Taller',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=32, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('cupos', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('revision', models.PositiveIntegerField(default=0, editable=False)),
            ],
            options={
                'db_table': 'talleres',
                'ordering': ['fecha_inicio', 'codigo'],
            },
        ),
        CreateOrAdoptModel(
            name='Inscripcion',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('confirmada', 'Confirmada')], default='confirmada', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscripciones', to='talleres.participante')),
                ('taller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscripciones', to='talleres.taller')),
            ],
            options={
                'db_table': 'inscripciones',
                'ordering': ['fecha_solicitud', 'id'],
                'constraints': [models.UniqueConstraint(fields=('participante', 'taller'), name='inscripcion_participante_taller_unica')],
            },
        ),
    ]
